# -*- coding: utf-8 -*-
"""PalmerPenguinsM6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eul0NaSnStbGJZXs9X0yquWFdiw05iGW
"""

# Palmer Penguins
# Raynette Brown
# 10.09.2026
# Use functions to organize Palmer Penguin analysis

#Import the math module
import math

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

# add constants for the number of penguins
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

# Define functions
def calculate_percentage(count, total):
    percentage = count / total * 100
    return percentage
# Function to classify by percentage
def classify_species(percent):
    if percent < 25:
        return "small"
    elif percent < 40:
        return "medium"
    else:
        return "large"
# Determine Relative Position
def get_position_description(selected_species, largest_species, smallest_species):
    if selected_species == largest_species:
        return "largest"
    elif selected_species == smallest_species:
        return "smallest"
    else:
        return "middle-sized"
# Function to display species stats
def display_species_statistics(names, counts, percentages):
    for index, species in enumerate(names):
        print(f"{species}: {counts[index]} "
              f"({percentages[index]:.2f}%)")
def main():
    # lists containing related penguin data
    species_names = [SP_CHINSTRAP, SP_GENTOO,SP_ADELIE]
    species_counts = [NUM_CHINSTRAP,NUM_GENTOO,NUM_ADELIE]

    # calculate dataset statistics
    total_species = len(species_names)
    total_penguins = sum(species_counts)

    # calculate penguin averages
    average_penguins = total_penguins / total_species
    average_penguins_rouneded_up = math.ceil(average_penguins)

    #Calculate the species percentages using function
    chinstrap_percent = \
    calculate_percentage(species_counts[0], total_penguins)
    gentoo_percent = \
    calculate_percentage(species_counts[1], total_penguins)
    adelie_percent = \
    calculate_percentage(species_counts[2], total_penguins)

    # Find largest and smallest species
    largest_count = max(species_counts)
    smallest_count = min(species_counts)
    largest_index = species_counts.index(largest_count)
    smallest_index = species_counts.index(smallest_count)
    largest_species = species_names[largest_index]
    smallest_species = species_names[smallest_index]

    # List of species percentages
    species_percentages = [chinstrap_percent, gentoo_percent,adelie_percent]

    # output the species names with introductory text

    print("Introducing the Palmer Penguins")
    print("\t" + SP_CHINSTRAP + "!")
    print("\t" + SP_GENTOO + "!")
    print("and last but not least...")
    print("\t" + SP_ADELIE + "!")
    print()

    print(f"There are a total of {total_penguins} penguins in the dataset.")
    print(f"The average number of penguins per species is "
    f"{average_penguins:.1f}.")
    print(f"The avergage number of penguins rounded up is {average_penguins_rouneded_up}.")
    print()

    #Display species statistics using function
    display_species_statistics(species_names, species_counts, species_percentages)
    print()
    print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
    print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")

    # prompt the user to select a species
    print()
    valid_selections = 0
    print("Explore a species")

    species_choice = input (
    "Enter Chinstrap, Gentoo, or Adelie, or Done: ")

    # Continue exploring species until the user enters Done
    while species_choice != "Done":
        # Validate species selection
        if species_choice not in species_names:
            print(species_choice + " is not one of the species in this dataset")
        else:
            valid_selections += 1
            # Determine the selected species index
            if species_choice == SP_CHINSTRAP:
                selected_index = 0
            elif species_choice == SP_GENTOO:
                selected_index = 1
            else:
                selected_index = 2

            # Classify the selected species
            selected_species = species_names[selected_index]
            selected_count = species_counts[selected_index]
            selected_percent = species_percentages[selected_index]

            # Size Category using function
            size_category = classify_species(selected_percent)

            # Determine relative position using function
            position_description = \
                        get_position_description(selected_species, \
                        largest_species, smallest_species)
            # Selected species count by average
            average_position = ("above" if selected_count > average_penguins else "below")

            #Display the selected species stats
            print()
            print(f"{selected_species} has {selected_count} observations, "
                      f"representing {selected_percent:.2f}% of the dataset.")
            print(f"{selected_species} is classified as a "
                      f"{size_category} species group.")
            print(f"{selected_species} is the {position_description} "
                      f"species group.")
            print(f"Its observation count is {average_position} "
                      f"the dataset average of {average_penguins:.1f}.")

        # Ask for another species
        print()
        species_choice = input("Enter Chinstrap, Gentoo, Adelie, or Done: ")

    print()
    print(f"You explored {valid_selections} valid species.")
    print("Exploration complete.")

main()